refactor ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,67 +14,151 @@ jobs:
     steps:
       - name: Check out the codebase
         uses: actions/checkout@v3
-
       - name: Set up Python 3
         uses: actions/setup-python@v3
-
       - name: Install test dependencies
         run: pip3 install yamllint ansible ansible-lint
-
       - name: Lint code
         uses: pre-commit/action@v3.0.0
-  integration-test:
-    name: Integration test
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os:
-          - macos-latest
-          - macos-13
-    steps:
-      - name: Check out the codebase.
-        uses: actions/checkout@v2
-
-      - name: Set up Python 3
-        uses: actions/setup-python@v3
-
-      - name: Install test dependencies
-        run: pip3 install yamllint ansible ansible-lint
-
-      - name: Uninstall GitHub Actions' built-in Homebrew.
-        run: |
-          if which brew > /dev/null; then
-            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
-          fi
-
-      - name: Uninstall GitHub Actions' built-in browser installs.
-        run: |
-          sudo rm -rf /Applications/Google\ Chrome.app
-          sudo rm -rf /usr/local/bin/chromedriver
-          sudo rm -rf /Applications/Firefox.app
-          sudo rm -rf /usr/local/bin/firefox
-
-      - name: Install test dependencies.
-        run: |
-          python3 -m pip install --upgrade pip
-          python3 -m pip install --user ansible
-
-      - name: Set up the test environment.
-        run: |
-          ansible-galaxy install -r requirements.yml
-
       - name: Test the playbook's syntax.
         run: ansible-playbook --inventory ./localhost --syntax-check test.yml
-
+  customize_dock_test:
+    name: Role customize_dock test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
       - name: Test the playbook.
-        run: ansible-playbook --inventory ./localhost test.yml
+        run:
+          ansible-playbook --inventory ./localhost roles/customize_dock/test.yml
         env:
           ANSIBLE_FORCE_COLOR: "1"
-
-      - name: Idempotence check.
-        run: |
-          idempotence=$(mktemp)
-          ansible-playbook --inventory ./localhost test.yml | tee -a ${idempotence}
-          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+  setup_git_test:
+    name: Role setup_git test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run: ansible-playbook --inventory ./localhost roles/setup_git/test.yml
         env:
           ANSIBLE_FORCE_COLOR: "1"
+  setup_ssh_test:
+    name: Role setup_ssh test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run: ansible-playbook --inventory ./localhost roles/setup_ssh/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  install_applications_test:
+    name: Role install_applications test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run:
+          ansible-playbook --inventory ./localhost
+          roles/install_applications/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  setup_java_test:
+    name: Role setup_java test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run: ansible-playbook --inventory ./localhost roles/setup_java/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  setup_zsh_test:
+    name: Role setup_zsh test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run: ansible-playbook --inventory ./localhost roles/setup_zsh/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  launch_applications_first_time_test:
+    name: Role launch_applications_first_time test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run:
+          ansible-playbook --inventory ./localhost
+          roles/launch_applications_first_time/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  setup_node_test:
+    name: Role setup_node test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run: ansible-playbook --inventory ./localhost roles/setup_node/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  setup_finicky_test:
+    name: Role setup_finicky test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run:
+          ansible-playbook --inventory ./localhost roles/setup_finicky/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  setup_python_test:
+    name: Role setup_python test
+    runs-on: macos-latest
+    steps:
+      - name: Check out the codebase
+        uses: actions/checkout@v3
+      - uses: .github/actions/setup
+      - name: Test the playbook.
+        run:
+          ansible-playbook --inventory ./localhost roles/setup_python/test.yml
+        env:
+          ANSIBLE_FORCE_COLOR: "1"
+  # integration-test:
+  #   name: Integration test
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os:
+  #         - macos-latest
+  #         - macos-13
+  #   steps:
+  #     - name: Check out the codebase.
+  #       uses: actions/checkout@v3
+  #     - uses: .github/actions/setup
+  #     - name: Test the playbook.
+  #       run: ansible-playbook --inventory ./localhost test.yml
+  #       env:
+  #         ANSIBLE_FORCE_COLOR: "1"
+  #     - name: Idempotence check.
+  #       run: |
+  #         idempotence=$(mktemp)
+  #         ansible-playbook --inventory ./localhost test.yml | tee -a ${idempotence}
+  #         tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+  #       env:
+  #         ANSIBLE_FORCE_COLOR: "1"
